// KineticOs — Módulo workout
// Ejercicios, músculos, rutinas, generación de entrenamientos. Media en MinIO.
dependencies {
    api project(':modules:shared')

    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.validation
    implementation libs.minio

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testImplementation libs.spring.boot.starter.test
    testImplementation libs.testcontainers.postgresql
}
