-- Amplía el catálogo de ejercicios de 52 a 106 usando free-exercise-db (dominio
-- público, ver V13) como fuente de referencia — nombres, descripciones e instrucciones
-- traducidos y adaptados al español, no son una traducción literal. Todas las URLs de
-- imagen fueron verificadas (HTTP 200) antes de esta migración.
INSERT INTO workout_exercises (id, name, description, category, equipment, difficulty, instructions, image_url, measurement_type) VALUES
    (53, 'Press de banca declinado', 'Empuje de barra en banco declinado.', 'strength', '["barbell", "bench"]', 'intermediate', 'Acostado en banco declinado, baja la barra al pecho bajo y empuja hacia arriba.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg', 'reps'),
    (54, 'Flexiones de brazos', 'Flexión de brazos apoyado en el suelo.', 'strength', '["bodyweight"]', 'beginner', 'Baja el pecho hacia el suelo manteniendo el cuerpo recto y empuja hacia arriba.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg', 'reps'),
    (55, 'Cruce de poleas', 'Aducción de brazos en polea alta, de pie.', 'strength', '["cable"]', 'intermediate', 'Con los cables en alto, junta las manos al frente del cuerpo en un arco descendente.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg', 'reps'),
    (56, 'Jalón al pecho agarre cerrado', 'Tracción de polea alta con agarre cerrado.', 'strength', '["cable"]', 'beginner', 'Tira de la barra en V hacia el pecho manteniendo los codos cerca del cuerpo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg', 'reps'),
    (57, 'Encogimientos con barra', 'Elevación de hombros sosteniendo una barra.', 'strength', '["barbell"]', 'beginner', 'Sostén la barra con los brazos extendidos y eleva los hombros hacia las orejas.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg', 'reps'),
    (58, 'Peso muerto piernas rígidas con barra', 'Peso muerto con piernas casi extendidas, foco en isquiosurales.', 'strength', '["barbell"]', 'intermediate', 'Con las rodillas casi rectas, baja la barra pegada a las piernas empujando la cadera atrás.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/0.jpg', 'reps'),
    (59, 'Remo al mentón con barra', 'Tracción vertical de barra hasta el pecho alto.', 'strength', '["barbell"]', 'intermediate', 'Tira de la barra hacia arriba pegada al cuerpo hasta la altura del pecho, codos por encima de las muñecas.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg', 'reps'),
    (60, 'Elevación posterior de hombro sentado', 'Elevación de mancuernas hacia atrás, inclinado, sentado.', 'strength', '["dumbbell", "bench"]', 'beginner', 'Inclinado hacia adelante sentado, eleva las mancuernas hacia los lados con leve flexión de codo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Bent-Over_Rear_Delt_Raise/0.jpg', 'reps'),
    (61, 'Press de hombros en máquina', 'Empuje vertical en máquina de press de hombros.', 'strength', '["machine"]', 'beginner', 'Ajusta el asiento y empuja las manijas hacia arriba sin bloquear del todo los codos.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Shoulder_Press/0.jpg', 'reps'),
    (62, 'Encogimientos con mancuernas', 'Elevación de hombros sosteniendo mancuernas.', 'strength', '["dumbbell"]', 'beginner', 'Con una mancuerna en cada mano, eleva los hombros hacia las orejas y baja controlado.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shrug/0.jpg', 'reps'),
    (63, 'Curl concentrado', 'Curl de bíceps con el codo apoyado en el muslo, sentado.', 'strength', '["dumbbell"]', 'beginner', 'Sentado, apoya el codo en la cara interna del muslo y flexiona el brazo hacia el hombro.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg', 'reps'),
    (64, 'Curl en banco Scott', 'Curl de bíceps con los brazos apoyados en un banco inclinado.', 'strength', '["barbell", "bench"]', 'beginner', 'Con los brazos apoyados en el banco Scott, sube la barra controlando la bajada.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg', 'reps'),
    (65, 'Fondos en banco', 'Fondos de tríceps apoyando las manos en un banco.', 'strength', '["bodyweight", "bench"]', 'beginner', 'Con las manos en el borde del banco y piernas extendidas, baja el cuerpo flexionando los codos.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'reps'),
    (66, 'Extensión de tríceps a un brazo', 'Extensión de tríceps por detrás de la cabeza con una mancuerna.', 'strength', '["dumbbell"]', 'intermediate', 'Con el codo apuntando arriba, baja la mancuerna detrás de la cabeza con un solo brazo y extiende.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_One-Arm_Triceps_Extension/0.jpg', 'reps'),
    (67, 'Sentadilla frontal', 'Sentadilla con la barra apoyada sobre los deltoides frontales.', 'strength', '["barbell", "rack"]', 'advanced', 'Con la barra sobre los hombros al frente y codos altos, baja en sentadilla manteniendo el torso erguido.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg', 'reps'),
    (68, 'Sentadilla Hack con barra', 'Sentadilla con la barra sostenida detrás de las piernas.', 'strength', '["barbell"]', 'advanced', 'Con la barra detrás de las piernas, baja en sentadilla manteniendo la espalda recta.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hack_Squat/0.jpg', 'reps'),
    (69, 'Zancada caminando', 'Zancadas alternadas avanzando, sin peso.', 'strength', '["bodyweight"]', 'beginner', 'Da un paso largo hacia adelante y baja hasta que ambas rodillas formen ~90°, alternando piernas al avanzar.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/0.jpg', 'reps'),
    (70, 'Aducción de cadera en polea', 'Cierre de pierna hacia el centro del cuerpo en polea baja.', 'strength', '["cable"]', 'beginner', 'Con el tobillo enganchado a la polea baja, lleva la pierna hacia el centro del cuerpo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Hip_Adduction/0.jpg', 'reps'),
    (71, 'Rueda abdominal', 'Extensión y retorno del cuerpo con una rueda abdominal.', 'strength', '["bodyweight"]', 'advanced', 'Desde rodillas, rueda hacia adelante extendiendo el cuerpo y vuelve a la posición inicial con el core firme.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg', 'reps'),
    (72, 'Elíptica', 'Cardio de bajo impacto en máquina elíptica.', 'cardio', '["machine"]', 'beginner', 'Mantén un ritmo constante empujando y tirando de los brazos junto con las piernas.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical_Trainer/0.jpg', 'reps'),
    (73, 'Escaladora', 'Cardio simulando subir escaleras en máquina.', 'cardio', '["machine"]', 'beginner', 'Sube los escalones a ritmo constante manteniendo el torso erguido.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stairmaster/0.jpg', 'reps'),
    (74, 'Salto al cajón', 'Salto explosivo sobre un cajón o plataforma.', 'plyometric', '["bodyweight"]', 'intermediate', 'Flexiona las rodillas y salta con ambos pies sobre el cajón, aterrizando suave.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Jump_Multiple_Response/0.jpg', 'reps'),
    (75, 'Clean con pesa rusa a un brazo', 'Levantamiento explosivo de pesa rusa hasta la posición de rack.', 'strength', '["kettlebell"]', 'advanced', 'Con un movimiento explosivo de cadera, lleva la pesa rusa desde el suelo hasta apoyarla en el antebrazo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Clean/0.jpg', 'reps'),
    (76, 'Crunch cruzado', 'Encogimiento abdominal llevando el codo hacia la rodilla contraria.', 'strength', '["bodyweight"]', 'beginner', 'Lleva el codo hacia la rodilla contraria elevando el torso, alternando lados.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross-Body_Crunch/0.jpg', 'reps'),
    (77, 'Estiramiento de pecho detrás de la cabeza', 'Estiramiento de pectoral entrelazando las manos detrás de la cabeza.', 'flexibility', '["bodyweight"]', 'beginner', 'Entrelaza las manos detrás de la cabeza y lleva los codos hacia atrás abriendo el pecho.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Behind_Head_Chest_Stretch/0.jpg', 'duration'),
    (78, 'Sentadilla sin peso', 'Sentadilla usando solo el peso corporal.', 'strength', '["bodyweight"]', 'beginner', 'Baja en sentadilla manteniendo el pecho arriba y las rodillas alineadas con los pies, sin ningún peso adicional.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/0.jpg', 'reps'),
    (79, 'Remo agarre supino', 'Remo con barra inclinado, agarre por debajo.', 'strength', '["barbell"]', 'intermediate', 'Inclinado hacia adelante con agarre supino, tira de la barra hacia el abdomen.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Bent-Over_Rows/0.jpg', 'reps'),
    (80, 'Flexiones declinadas', 'Flexión de brazos con los pies elevados.', 'strength', '["bodyweight", "bench"]', 'intermediate', 'Con los pies apoyados en un banco, baja el pecho hacia el suelo y empuja hacia arriba.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg', 'reps'),
    (81, 'Superman', 'Extensión simultánea de brazos y piernas boca abajo.', 'strength', '["bodyweight"]', 'beginner', 'Boca abajo, eleva brazos y piernas al mismo tiempo apretando la zona lumbar.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Superman/0.jpg', 'reps'),
    (82, 'Inchworm (oruga)', 'Movimiento de calentamiento caminando con las manos hasta plancha y volviendo.', 'mobility', '["bodyweight"]', 'beginner', 'Desde de pie, camina con las manos hacia adelante hasta la plancha y luego camina los pies hacia las manos.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inchworm/0.jpg', 'reps'),
    (83, 'Remo en T', 'Remo horizontal en máquina o barra en T.', 'strength', '["machine"]', 'intermediate', 'Inclinado sobre la barra en T, tira del agarre hacia el abdomen apretando la espalda.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle/0.jpg', 'reps'),
    (84, 'Press Arnold', 'Press de hombros con rotación de muñecas.', 'strength', '["dumbbell"]', 'intermediate', 'Empieza con las palmas hacia vos, sube las mancuernas rotando las muñecas hasta terminar con las palmas al frente.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg', 'reps'),
    (85, 'Curl en polea alta', 'Curl de bíceps con los brazos extendidos a la altura de los hombros.', 'strength', '["cable"]', 'intermediate', 'Con los codos a la altura de los hombros, flexiona los antebrazos hacia la cabeza.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg', 'reps'),
    (86, 'Jalón entre piernas en polea', 'Extensión de cadera tirando de una polea baja entre las piernas.', 'strength', '["cable"]', 'intermediate', 'De espaldas a la polea baja, empuja la cadera hacia adelante para llevar el cable entre las piernas hacia arriba.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pull_Through/0.jpg', 'reps'),
    (87, 'Elevación de piernas acostado', 'Elevación de piernas rectas acostado boca arriba.', 'strength', '["bodyweight"]', 'beginner', 'Acostado boca arriba, eleva las piernas rectas hasta 90° y baja controlado sin tocar el suelo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg', 'reps'),
    (88, 'Balanceo con pesa rusa a un brazo', 'Balanceo de pesa rusa entre las piernas hasta la altura del pecho.', 'strength', '["kettlebell"]', 'intermediate', 'Con un solo brazo, balancea la pesa rusa entre las piernas y empuja la cadera para llevarla hasta el pecho.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Kettlebell_Swings/0.jpg', 'reps'),
    (89, 'Remo renegado', 'Remo alternado con mancuernas en posición de plancha.', 'strength', '["dumbbell"]', 'advanced', 'En posición de plancha con una mancuerna en cada mano, rema alternando brazos sin rotar la cadera.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Renegade_Row/0.jpg', 'reps'),
    (90, 'Estiramiento de isquiotibiales', 'Estiramiento estático de la parte posterior del muslo.', 'flexibility', '["bodyweight"]', 'beginner', 'Sentado o de pie, estira la pierna e inclina el torso hacia adelante manteniendo la espalda recta.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hamstring_Stretch/0.jpg', 'duration'),
    (91, 'Estiramiento de cuádriceps en el suelo', 'Estiramiento de cuádriceps a cuatro patas.', 'flexibility', '["bodyweight"]', 'beginner', 'A cuatro patas, lleva un talón hacia el glúteo sosteniendo el pie con la mano.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/All_Fours_Quad_Stretch/0.jpg', 'duration'),
    (92, 'Buenos días (Good Morning)', 'Flexión de cadera con barra en la espalda, foco en isquiosurales y lumbar.', 'strength', '["barbell"]', 'advanced', 'Con la barra sobre los trapecios, flexiona la cadera hacia adelante manteniendo las rodillas casi rectas y la espalda neutra.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg', 'reps'),
    (93, 'Curl de muñeca con barra', 'Flexión de muñeca sosteniendo una barra, antebrazos apoyados.', 'strength', '["barbell", "bench"]', 'beginner', 'Con los antebrazos apoyados en el banco y palmas hacia arriba, flexiona las muñecas subiendo la barra.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Palms-Up_Barbell_Wrist_Curl_Over_A_Bench/0.jpg', 'reps'),
    (94, 'Aperturas posteriores con mancuernas', 'Elevación de mancuernas hacia atrás, inclinado.', 'strength', '["dumbbell"]', 'beginner', 'Inclinado hacia adelante, eleva las mancuernas hacia los lados apretando los omóplatos.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Flyes/0.jpg', 'reps'),
    (95, 'Patada de glúteo en polea', 'Extensión de cadera hacia atrás en polea baja, una pierna.', 'strength', '["cable"]', 'beginner', 'Con el tobillo enganchado a la polea baja, extiende la pierna hacia atrás apretando el glúteo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Legged_Cable_Kickback/0.jpg', 'reps'),
    (96, 'Patada de tijera (Flutter Kicks)', 'Batido de piernas alternado acostado boca arriba.', 'strength', '["bodyweight"]', 'beginner', 'Acostado boca arriba con piernas rectas levemente elevadas, alterna el batido de piernas.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flutter_Kicks/0.jpg', 'reps'),
    (97, 'Press de hombros con mancuernas sentado', 'Empuje de mancuernas por encima de la cabeza, sentado.', 'strength', '["dumbbell", "bench"]', 'beginner', 'Sentado con respaldo, empuja las mancuernas desde los hombros hasta extender los brazos arriba.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Press/0.jpg', 'reps'),
    (98, 'Curl de bíceps en banco inclinado', 'Curl de bíceps con los brazos colgando en un banco inclinado.', 'strength', '["dumbbell", "bench"]', 'intermediate', 'Sentado en banco inclinado con los brazos colgando, flexiona los codos subiendo las mancuernas.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg', 'reps'),
    (99, 'Apertura con banda', 'Apertura horizontal de brazos estirando una banda elástica.', 'strength', '["bands"]', 'beginner', 'Con la banda tensa al frente a la altura de los hombros, separa los brazos hacia los lados apretando los omóplatos.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Pull_Apart/0.jpg', 'reps'),
    (100, 'Puente de glúteo a una pierna', 'Elevación de cadera apoyado en una sola pierna.', 'strength', '["bodyweight"]', 'intermediate', 'Acostado con una pierna flexionada y la otra extendida, eleva la cadera apretando el glúteo de apoyo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg', 'reps'),
    (101, 'Estiramiento de gemelos contra la pared', 'Estiramiento de pantorrilla apoyando las manos en la pared.', 'flexibility', '["bodyweight"]', 'beginner', 'Con las manos en la pared, lleva una pierna atrás con el talón apoyado y empuja la cadera hacia adelante.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Stretch_Hands_Against_Wall/0.jpg', 'duration'),
    (102, 'Postura del niño', 'Estiramiento de espalda baja y cadera, de rodillas.', 'flexibility', '["bodyweight"]', 'beginner', 'De rodillas, siéntate sobre los talones y estira los brazos hacia adelante bajando el pecho al suelo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Childs_Pose/0.jpg', 'duration'),
    (103, 'Estiramiento espinal', 'Estiramiento de columna sentado con piernas extendidas.', 'flexibility', '["bodyweight"]', 'beginner', 'Sentado con las piernas extendidas, inclina el torso hacia adelante buscando los pies.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spinal_Stretch/0.jpg', 'duration'),
    (104, 'Estiramiento de hombro', 'Estiramiento cruzando un brazo por delante del cuerpo.', 'flexibility', '["bodyweight"]', 'beginner', 'Cruza un brazo por delante del pecho y presiona suavemente con el otro brazo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Shoulder_Stretch/0.jpg', 'duration'),
    (105, 'Estiramiento de tríceps', 'Estiramiento de tríceps con el brazo detrás de la cabeza.', 'flexibility', '["bodyweight"]', 'beginner', 'Lleva un brazo detrás de la cabeza y empuja suavemente el codo con la otra mano.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Stretch/0.jpg', 'duration'),
    (106, 'Dead Bug', 'Ejercicio de estabilidad de core extendiendo brazo y pierna opuestos.', 'strength', '["bodyweight"]', 'beginner', 'Acostado boca arriba con brazos y piernas en el aire, extiende un brazo y la pierna opuesta sin despegar la espalda del suelo.', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg', 'reps');

INSERT INTO workout_exercise_muscles (exercise_id, muscle_id, role) VALUES
    (53, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'primary'),
    (53, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'secondary'),
    (54, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'primary'),
    (54, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'secondary'),
    (54, (SELECT id FROM workout_muscles WHERE code = 'anterior_delts'), 'secondary'),
    (55, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'primary'),
    (56, (SELECT id FROM workout_muscles WHERE code = 'lats'), 'primary'),
    (56, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'secondary'),
    (57, (SELECT id FROM workout_muscles WHERE code = 'traps'), 'primary'),
    (58, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'primary'),
    (58, (SELECT id FROM workout_muscles WHERE code = 'lower_back'), 'secondary'),
    (59, (SELECT id FROM workout_muscles WHERE code = 'lateral_delts'), 'primary'),
    (59, (SELECT id FROM workout_muscles WHERE code = 'traps'), 'secondary'),
    (60, (SELECT id FROM workout_muscles WHERE code = 'posterior_delts'), 'primary'),
    (61, (SELECT id FROM workout_muscles WHERE code = 'anterior_delts'), 'primary'),
    (61, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'secondary'),
    (62, (SELECT id FROM workout_muscles WHERE code = 'traps'), 'primary'),
    (63, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'primary'),
    (64, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'primary'),
    (65, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'primary'),
    (65, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'secondary'),
    (66, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'primary'),
    (67, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (67, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (68, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (68, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (69, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (69, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (70, (SELECT id FROM workout_muscles WHERE code = 'adductors'), 'primary'),
    (71, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'primary'),
    (72, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (72, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (73, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (73, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (74, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (74, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (75, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'primary'),
    (75, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (76, (SELECT id FROM workout_muscles WHERE code = 'obliques'), 'primary'),
    (76, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'secondary'),
    (77, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'primary'),
    (78, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (78, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (79, (SELECT id FROM workout_muscles WHERE code = 'lats'), 'primary'),
    (79, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'secondary'),
    (80, (SELECT id FROM workout_muscles WHERE code = 'pecs'), 'primary'),
    (80, (SELECT id FROM workout_muscles WHERE code = 'anterior_delts'), 'secondary'),
    (81, (SELECT id FROM workout_muscles WHERE code = 'lower_back'), 'primary'),
    (81, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'secondary'),
    (82, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'primary'),
    (82, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'secondary'),
    (83, (SELECT id FROM workout_muscles WHERE code = 'lats'), 'primary'),
    (83, (SELECT id FROM workout_muscles WHERE code = 'rhomboids'), 'secondary'),
    (84, (SELECT id FROM workout_muscles WHERE code = 'anterior_delts'), 'primary'),
    (84, (SELECT id FROM workout_muscles WHERE code = 'lateral_delts'), 'secondary'),
    (85, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'primary'),
    (86, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'primary'),
    (86, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (87, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'primary'),
    (87, (SELECT id FROM workout_muscles WHERE code = 'hip_flexors'), 'secondary'),
    (88, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'primary'),
    (88, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (89, (SELECT id FROM workout_muscles WHERE code = 'lats'), 'primary'),
    (89, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'secondary'),
    (90, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'primary'),
    (91, (SELECT id FROM workout_muscles WHERE code = 'quads'), 'primary'),
    (92, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'primary'),
    (92, (SELECT id FROM workout_muscles WHERE code = 'lower_back'), 'secondary'),
    (93, (SELECT id FROM workout_muscles WHERE code = 'forearms'), 'primary'),
    (94, (SELECT id FROM workout_muscles WHERE code = 'posterior_delts'), 'primary'),
    (94, (SELECT id FROM workout_muscles WHERE code = 'rhomboids'), 'secondary'),
    (95, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'primary'),
    (95, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (96, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'primary'),
    (96, (SELECT id FROM workout_muscles WHERE code = 'hip_flexors'), 'secondary'),
    (97, (SELECT id FROM workout_muscles WHERE code = 'anterior_delts'), 'primary'),
    (97, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'secondary'),
    (98, (SELECT id FROM workout_muscles WHERE code = 'biceps'), 'primary'),
    (99, (SELECT id FROM workout_muscles WHERE code = 'posterior_delts'), 'primary'),
    (99, (SELECT id FROM workout_muscles WHERE code = 'rhomboids'), 'secondary'),
    (100, (SELECT id FROM workout_muscles WHERE code = 'glutes'), 'primary'),
    (100, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (101, (SELECT id FROM workout_muscles WHERE code = 'calves'), 'primary'),
    (102, (SELECT id FROM workout_muscles WHERE code = 'lower_back'), 'primary'),
    (102, (SELECT id FROM workout_muscles WHERE code = 'lats'), 'secondary'),
    (103, (SELECT id FROM workout_muscles WHERE code = 'lower_back'), 'primary'),
    (103, (SELECT id FROM workout_muscles WHERE code = 'hamstrings'), 'secondary'),
    (104, (SELECT id FROM workout_muscles WHERE code = 'posterior_delts'), 'primary'),
    (105, (SELECT id FROM workout_muscles WHERE code = 'triceps'), 'primary'),
    (106, (SELECT id FROM workout_muscles WHERE code = 'abs'), 'primary');

SELECT setval(pg_get_serial_sequence('workout_exercises', 'id'), (SELECT MAX(id) FROM workout_exercises));
